@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

call "%~dp0load_active_alpha_config.bat"

echo ============================================================
echo Active Alpha Trading 212 - Settings Wizard
echo ============================================================
echo.
echo Diese Einstellungen werden in active_alpha_user_config.bat gespeichert.
echo Backtest und Paper-Trading laden danach dieselben zentralen Werte.
echo.

set /p "USER_BENCHMARK=Benchmark [!AA_BENCHMARK!]: "
if not "!USER_BENCHMARK!"=="" set "AA_BENCHMARK=!USER_BENCHMARK!"

set /p "USER_START=Startdatum YYYY-MM-DD [!AA_START_DATE!]: "
if not "!USER_START!"=="" set "AA_START_DATE=!USER_START!"

set /p "USER_LOOKBACK=Signal-Lookback-Jahre [!AA_SIGNAL_LOOKBACK_YEARS!]: "
if not "!USER_LOOKBACK!"=="" set "AA_SIGNAL_LOOKBACK_YEARS=!USER_LOOKBACK!"

echo [INFO] Backtest- und Paper-Kapital sind getrennt.
set /p "USER_BACKTEST_CAPITAL=Backtest-Kapital USD [!AA_BACKTEST_CAPITAL!]: "
if not "!USER_BACKTEST_CAPITAL!"=="" set "AA_BACKTEST_CAPITAL=!USER_BACKTEST_CAPITAL!"
set "AA_BACKTEST_CAPITAL=!AA_BACKTEST_CAPITAL:,=.!"

set /p "USER_RESEARCH_CAPITAL=Research-Kapital fuer Backtest-Policy USD [!AA_RESEARCH_BACKTEST_CAPITAL!]: "
if not "!USER_RESEARCH_CAPITAL!"=="" set "AA_RESEARCH_BACKTEST_CAPITAL=!USER_RESEARCH_CAPITAL!"
set "AA_RESEARCH_BACKTEST_CAPITAL=!AA_RESEARCH_BACKTEST_CAPITAL:,=.!"

set /p "USER_PAPER_CAPITAL=Paper-Start-/Fallbackkapital USD [!AA_PAPER_CAPITAL!]: "
if not "!USER_PAPER_CAPITAL!"=="" set "AA_PAPER_CAPITAL=!USER_PAPER_CAPITAL!"
set "AA_PAPER_CAPITAL=!AA_PAPER_CAPITAL:,=.!"

set /p "USER_TOPN=Universe Top-N 100/150/250/500 [!AA_UNIVERSE_TOP_N!]: "
if not "!USER_TOPN!"=="" set "AA_UNIVERSE_TOP_N=!USER_TOPN!"

set /p "USER_POLICY=Trading-212-Policy conservative/balanced/active/threshold [!AA_TRADING212_POLICY!]: "
if not "!USER_POLICY!"=="" set "AA_TRADING212_POLICY=!USER_POLICY!"

set /p "USER_EXEC_MODE=Execution Policy Mode manual/capital_curve [!AA_EXECUTION_POLICY_MODE!]: "
if not "!USER_EXEC_MODE!"=="" set "AA_EXECUTION_POLICY_MODE=!USER_EXEC_MODE!"

call :ValidatePolicyInputs

echo.
if /I "!AA_EXECUTION_POLICY_MODE!"=="capital_curve" (
  echo [INFO] Aktive Profilsteuerung: capital_curve / !AA_TRADING212_POLICY!
  echo [INFO] Rebalance Every, Top-K, Max Position, Max Issuer, No-Trade-Band und Max Turnover werden im Lauf durch die Trading-212-Policy ueberschrieben.
) else (
  echo [INFO] Manual-Modus aktiv: Rebalance Every, Top-K und weitere erweiterte Modellparameter wirken direkt.
)

set /p "USER_SLIP=Slippage BPS [!AA_SLIPPAGE_BPS!]: "
if not "!USER_SLIP!"=="" set "AA_SLIPPAGE_BPS=!USER_SLIP!"
set "AA_SLIPPAGE_BPS=!AA_SLIPPAGE_BPS:,=.!"

set /p "USER_FX=Trading-212 FX BPS [!AA_TRADING212_FX_BPS!]: "
if not "!USER_FX!"=="" set "AA_TRADING212_FX_BPS=!USER_FX!"
set "AA_TRADING212_FX_BPS=!AA_TRADING212_FX_BPS:,=.!"

set /p "USER_IMPACT=Market Impact BPS [!AA_MARKET_IMPACT_BPS!]: "
if not "!USER_IMPACT!"=="" set "AA_MARKET_IMPACT_BPS=!USER_IMPACT!"
set "AA_MARKET_IMPACT_BPS=!AA_MARKET_IMPACT_BPS:,=.!"

set /p "USER_BACKTEST_SOURCE=Backtest-Tickerquelle [!AA_BACKTEST_TICKER_SOURCE!]: "
if not "!USER_BACKTEST_SOURCE!"=="" set "AA_BACKTEST_TICKER_SOURCE=!USER_BACKTEST_SOURCE!"

set /p "USER_PAPER_SOURCE=Paper-Tickerquelle [!AA_PAPER_TICKER_SOURCE!]: "
if not "!USER_PAPER_SOURCE!"=="" set "AA_PAPER_TICKER_SOURCE=!USER_PAPER_SOURCE!"

set /p "USER_MEMBERSHIP_FILE=Membership-Datei [!AA_MEMBERSHIP_FILE!]: "
if not "!USER_MEMBERSHIP_FILE!"=="" set "AA_MEMBERSHIP_FILE=!USER_MEMBERSHIP_FILE!"

set /p "USER_BACKTEST_MEMBERSHIP=Backtest Membership Mode off/auto/strict [!AA_BACKTEST_MEMBERSHIP_MODE!]: "
if not "!USER_BACKTEST_MEMBERSHIP!"=="" set "AA_BACKTEST_MEMBERSHIP_MODE=!USER_BACKTEST_MEMBERSHIP!"

set /p "USER_PAPER_MEMBERSHIP=Paper Membership Mode off/auto/strict [!AA_PAPER_MEMBERSHIP_MODE!]: "
if not "!USER_PAPER_MEMBERSHIP!"=="" set "AA_PAPER_MEMBERSHIP_MODE=!USER_PAPER_MEMBERSHIP!"

set /p "USER_MAX_GROSS=Max Gross Exposure [!AA_MAX_GROSS_EXPOSURE!]: "
if not "!USER_MAX_GROSS!"=="" set "AA_MAX_GROSS_EXPOSURE=!USER_MAX_GROSS!"
set "AA_MAX_GROSS_EXPOSURE=!AA_MAX_GROSS_EXPOSURE:,=.!"

echo.
echo Tail-Pruning / Positionshygiene
if /I "!AA_TAIL_PRUNE_ENABLED!"=="N" (set "TP_PROMPT=j/N [N]") else (set "TP_PROMPT=J/n [J]")
set /p "USER_TAIL_PRUNE=Tail-Prune aktivieren? !TP_PROMPT!: "
if not "!USER_TAIL_PRUNE!"=="" set "AA_TAIL_PRUNE_ENABLED=!USER_TAIL_PRUNE!"

set /p "USER_RESIDUAL_FLOOR=Residual Weight Floor [!AA_RESIDUAL_WEIGHT_FLOOR!]: "
if not "!USER_RESIDUAL_FLOOR!"=="" set "AA_RESIDUAL_WEIGHT_FLOOR=!USER_RESIDUAL_FLOOR!"
set "AA_RESIDUAL_WEIGHT_FLOOR=!AA_RESIDUAL_WEIGHT_FLOOR:,=.!"

set /p "USER_RESIDUAL_SELL_MIN=Residual Sell Min Value USD [!AA_RESIDUAL_SELL_MIN_VALUE!]: "
if not "!USER_RESIDUAL_SELL_MIN!"=="" set "AA_RESIDUAL_SELL_MIN_VALUE=!USER_RESIDUAL_SELL_MIN!"
set "AA_RESIDUAL_SELL_MIN_VALUE=!AA_RESIDUAL_SELL_MIN_VALUE:,=.!"

set /p "USER_ORDER_VALUE_ROUNDING=Order Value Rounding USD, 1.0=volle Dollar, 0=aus [!AA_ORDER_VALUE_ROUNDING!]: "
if not "!USER_ORDER_VALUE_ROUNDING!"=="" set "AA_ORDER_VALUE_ROUNDING=!USER_ORDER_VALUE_ROUNDING!"
set "AA_ORDER_VALUE_ROUNDING=!AA_ORDER_VALUE_ROUNDING:,=.!"

set /p "USER_MIN_REMAINING=Broker Min Remaining Position Value USD [!AA_BROKER_MIN_REMAINING_POSITION_VALUE!]: "
if not "!USER_MIN_REMAINING!"=="" set "AA_BROKER_MIN_REMAINING_POSITION_VALUE=!USER_MIN_REMAINING!"
set "AA_BROKER_MIN_REMAINING_POSITION_VALUE=!AA_BROKER_MIN_REMAINING_POSITION_VALUE:,=.!"

set /p "USER_POS_SOFT=Max Positions Soft [!AA_MAX_N_POSITIONS_SOFT!]: "
if not "!USER_POS_SOFT!"=="" set "AA_MAX_N_POSITIONS_SOFT=!USER_POS_SOFT!"

set /p "USER_POS_HARD=Max Positions Hard [!AA_MAX_N_POSITIONS_HARD!]: "
if not "!USER_POS_HARD!"=="" set "AA_MAX_N_POSITIONS_HARD=!USER_POS_HARD!"

if /I "!AA_TAIL_PRUNE_REALLOCATE!"=="N" (set "TP_REALLOC_PROMPT=j/N [N]") else (set "TP_REALLOC_PROMPT=J/n [J]")
set /p "USER_TAIL_REALLOC=Tail-Prune Reallocate? !TP_REALLOC_PROMPT!: "
if not "!USER_TAIL_REALLOC!"=="" set "AA_TAIL_PRUNE_REALLOCATE=!USER_TAIL_REALLOC!"

set /p "USER_TAIL_REALLOC_NAME=Max Tail Reallocation per Name [!AA_MAX_TAIL_REALLOCATION_PER_NAME!]: "
if not "!USER_TAIL_REALLOC_NAME!"=="" set "AA_MAX_TAIL_REALLOCATION_PER_NAME=!USER_TAIL_REALLOC_NAME!"
set "AA_MAX_TAIL_REALLOCATION_PER_NAME=!AA_MAX_TAIL_REALLOCATION_PER_NAME:,=.!"

set /p "USER_TAIL_REALLOC_STEP=Tail Reallocation Step [!AA_TAIL_REALLOCATION_STEP!]: "
if not "!USER_TAIL_REALLOC_STEP!"=="" set "AA_TAIL_REALLOCATION_STEP=!USER_TAIL_REALLOC_STEP!"
set "AA_TAIL_REALLOCATION_STEP=!AA_TAIL_REALLOCATION_STEP:,=.!"

set /p "USER_TAIL_REALLOC_ROUNDS=Tail Reallocation Rounds [!AA_TAIL_REALLOCATION_ROUNDS!]: "
if not "!USER_TAIL_REALLOC_ROUNDS!"=="" set "AA_TAIL_REALLOCATION_ROUNDS=!USER_TAIL_REALLOC_ROUNDS!"

set /p "USER_TAIL_EXPOSURE_BUFFER=Tail-Prune Min Exposure Buffer [!AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER!]: "
if not "!USER_TAIL_EXPOSURE_BUFFER!"=="" set "AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER=!USER_TAIL_EXPOSURE_BUFFER!"
set "AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER=!AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER:,=.!"

set /p "USER_OUT_BACKTEST=Backtest Output-Ordner [!AA_BACKTEST_OUT_DIR!]: "
if not "!USER_OUT_BACKTEST!"=="" set "AA_BACKTEST_OUT_DIR=!USER_OUT_BACKTEST!"

set /p "USER_OUT_PAPER_MODEL=Paper Model Output-Ordner [!AA_PAPER_MODEL_OUT_DIR!]: "
if not "!USER_OUT_PAPER_MODEL!"=="" set "AA_PAPER_MODEL_OUT_DIR=!USER_OUT_PAPER_MODEL!"

set /p "USER_PAPER_DIR=Paper Depot-Ordner [!AA_PAPER_DIR!]: "
if not "!USER_PAPER_DIR!"=="" set "AA_PAPER_DIR=!USER_PAPER_DIR!"

echo.
set /p "ADVANCED=Erweiterte Modellparameter bearbeiten? j/N [N]: "
if /I "!ADVANCED!"=="J" (
  set "POLICY_FIELD_PREFIX="
  if /I "!AA_EXECUTION_POLICY_MODE!"=="capital_curve" (
    set "POLICY_FIELD_PREFIX=Manual-Fallback "
    echo.
    echo [INFO] capital_curve ist aktiv. Die gleichnamigen Profilfelder unten werden gespeichert,
    echo [INFO] aber bei Modell-/Paper-Laeufen durch !AA_TRADING212_POLICY! kapitalabhaengig ueberschrieben.
  )

  set /p "USER_HORIZON=Horizon [!AA_HORIZON!]: "
  if not "!USER_HORIZON!"=="" set "AA_HORIZON=!USER_HORIZON!"

  set /p "USER_REBALANCE_EVERY=!POLICY_FIELD_PREFIX!Rebalance Every [!AA_REBALANCE_EVERY!]: "
  if not "!USER_REBALANCE_EVERY!"=="" set "AA_REBALANCE_EVERY=!USER_REBALANCE_EVERY!"

  set /p "USER_TOP_K=!POLICY_FIELD_PREFIX!Top-K [!AA_TOP_K!]: "
  if not "!USER_TOP_K!"=="" set "AA_TOP_K=!USER_TOP_K!"

  set /p "USER_MAX_POSITION=!POLICY_FIELD_PREFIX!Max Position [!AA_MAX_POSITION!]: "
  if not "!USER_MAX_POSITION!"=="" set "AA_MAX_POSITION=!USER_MAX_POSITION!"
  set "AA_MAX_POSITION=!AA_MAX_POSITION:,=.!"

  set /p "USER_MAX_ISSUER=!POLICY_FIELD_PREFIX!Max Issuer [!AA_MAX_ISSUER!]: "
  if not "!USER_MAX_ISSUER!"=="" set "AA_MAX_ISSUER=!USER_MAX_ISSUER!"
  set "AA_MAX_ISSUER=!AA_MAX_ISSUER:,=.!"

  set /p "USER_MAX_SECTOR=Max Sector [!AA_MAX_SECTOR!]: "
  if not "!USER_MAX_SECTOR!"=="" set "AA_MAX_SECTOR=!USER_MAX_SECTOR!"
  set "AA_MAX_SECTOR=!AA_MAX_SECTOR:,=.!"

  set /p "USER_MAX_CLUSTER=Max Correlation Cluster [!AA_MAX_CORRELATION_CLUSTER!]: "
  if not "!USER_MAX_CLUSTER!"=="" set "AA_MAX_CORRELATION_CLUSTER=!USER_MAX_CLUSTER!"
  set "AA_MAX_CORRELATION_CLUSTER=!AA_MAX_CORRELATION_CLUSTER:,=.!"

  set /p "USER_MAX_BETA=Max Portfolio Beta [!AA_MAX_PORTFOLIO_BETA!]: "
  if not "!USER_MAX_BETA!"=="" set "AA_MAX_PORTFOLIO_BETA=!USER_MAX_BETA!"
  set "AA_MAX_PORTFOLIO_BETA=!AA_MAX_PORTFOLIO_BETA:,=.!"

  set /p "USER_BETA_CAP_MODE=Beta Cap Mode fixed/dynamic [!AA_BETA_CAP_MODE!]: "
  if not "!USER_BETA_CAP_MODE!"=="" set "AA_BETA_CAP_MODE=!USER_BETA_CAP_MODE!"

  set /p "USER_DYN_BETA_OFF=Dynamic Beta Risk-Off [!AA_DYNAMIC_BETA_RISK_OFF!]: "
  if not "!USER_DYN_BETA_OFF!"=="" set "AA_DYNAMIC_BETA_RISK_OFF=!USER_DYN_BETA_OFF!"
  set "AA_DYNAMIC_BETA_RISK_OFF=!AA_DYNAMIC_BETA_RISK_OFF:,=.!"

  set /p "USER_DYN_BETA_NORMAL=Dynamic Beta Normal [!AA_DYNAMIC_BETA_NORMAL!]: "
  if not "!USER_DYN_BETA_NORMAL!"=="" set "AA_DYNAMIC_BETA_NORMAL=!USER_DYN_BETA_NORMAL!"
  set "AA_DYNAMIC_BETA_NORMAL=!AA_DYNAMIC_BETA_NORMAL:,=.!"

  set /p "USER_DYN_BETA_RISKON=Dynamic Beta Risk-On [!AA_DYNAMIC_BETA_RISK_ON!]: "
  if not "!USER_DYN_BETA_RISKON!"=="" set "AA_DYNAMIC_BETA_RISK_ON=!USER_DYN_BETA_RISKON!"
  set "AA_DYNAMIC_BETA_RISK_ON=!AA_DYNAMIC_BETA_RISK_ON:,=.!"

  set /p "USER_DYN_BETA_STRONG=Dynamic Beta Strong [!AA_DYNAMIC_BETA_STRONG!]: "
  if not "!USER_DYN_BETA_STRONG!"=="" set "AA_DYNAMIC_BETA_STRONG=!USER_DYN_BETA_STRONG!"
  set "AA_DYNAMIC_BETA_STRONG=!AA_DYNAMIC_BETA_STRONG:,=.!"

  set /p "USER_STATIC_CLUSTER_CAP=Static Cluster Cap [!AA_STATIC_CLUSTER_CAP!]: "
  if not "!USER_STATIC_CLUSTER_CAP!"=="" set "AA_STATIC_CLUSTER_CAP=!USER_STATIC_CLUSTER_CAP!"
  set "AA_STATIC_CLUSTER_CAP=!AA_STATIC_CLUSTER_CAP:,=.!"

  set /p "USER_DYNAMIC_CLUSTER_CAP=Dynamic Cluster Cap [!AA_DYNAMIC_CLUSTER_CAP!]: "
  if not "!USER_DYNAMIC_CLUSTER_CAP!"=="" set "AA_DYNAMIC_CLUSTER_CAP=!USER_DYNAMIC_CLUSTER_CAP!"
  set "AA_DYNAMIC_CLUSTER_CAP=!AA_DYNAMIC_CLUSTER_CAP:,=.!"

  set /p "USER_CLUSTER_CONSTRAINT_MODE=Cluster Constraint Mode static_only/dynamic_only/both_restrictive [!AA_CLUSTER_CONSTRAINT_MODE!]: "
  if not "!USER_CLUSTER_CONSTRAINT_MODE!"=="" set "AA_CLUSTER_CONSTRAINT_MODE=!USER_CLUSTER_CONSTRAINT_MODE!"

  set /p "USER_NO_TRADE_BAND=!POLICY_FIELD_PREFIX!No-Trade-Band [!AA_NO_TRADE_BAND!]: "
  if not "!USER_NO_TRADE_BAND!"=="" set "AA_NO_TRADE_BAND=!USER_NO_TRADE_BAND!"
  set "AA_NO_TRADE_BAND=!AA_NO_TRADE_BAND:,=.!"

  set /p "USER_WEIGHT_SMOOTHING=Weight Smoothing [!AA_WEIGHT_SMOOTHING!]: "
  if not "!USER_WEIGHT_SMOOTHING!"=="" set "AA_WEIGHT_SMOOTHING=!USER_WEIGHT_SMOOTHING!"
  set "AA_WEIGHT_SMOOTHING=!AA_WEIGHT_SMOOTHING:,=.!"

  set /p "USER_MAX_TURNOVER=!POLICY_FIELD_PREFIX!Max Turnover [!AA_MAX_TURNOVER!]: "
  if not "!USER_MAX_TURNOVER!"=="" set "AA_MAX_TURNOVER=!USER_MAX_TURNOVER!"
  set "AA_MAX_TURNOVER=!AA_MAX_TURNOVER:,=.!"

  echo.
  echo Erweiterte Validierungs-/Modelllogik
  set /p "USER_ALPHA_MODEL_MODE=Alpha Model Mode ensemble/ml_only/rank_only/elastic_only/gbm_only [!AA_ALPHA_MODEL_MODE!]: "
  if not "!USER_ALPHA_MODEL_MODE!"=="" set "AA_ALPHA_MODEL_MODE=!USER_ALPHA_MODEL_MODE!"

  set /p "USER_EXTRA_BENCH=Extra Benchmarks CSV [!AA_EXTRA_BENCHMARKS!]: "
  if not "!USER_EXTRA_BENCH!"=="" set "AA_EXTRA_BENCHMARKS=!USER_EXTRA_BENCH!"

  set /p "USER_NAIVE_VARIANTS=Naive Momentum Variants CSV [!AA_NAIVE_MOMENTUM_VARIANTS!]: "
  if not "!USER_NAIVE_VARIANTS!"=="" set "AA_NAIVE_MOMENTUM_VARIANTS=!USER_NAIVE_VARIANTS!"

  set /p "USER_BOOTSTRAP=Bootstrap Iterations [!AA_BOOTSTRAP_ITERATIONS!]: "
  if not "!USER_BOOTSTRAP!"=="" set "AA_BOOTSTRAP_ITERATIONS=!USER_BOOTSTRAP!"

  set /p "USER_RISK_MODE=Risk-Regime Mode strict/normal/loose [!AA_RISK_REGIME_MODE!]: "
  if not "!USER_RISK_MODE!"=="" set "AA_RISK_REGIME_MODE=!USER_RISK_MODE!"

  set /p "USER_EXPOSURE_CONTROLLER=Exposure Controller binary/gradual/gradual_alpha [!AA_EXPOSURE_CONTROLLER!]: "
  if not "!USER_EXPOSURE_CONTROLLER!"=="" set "AA_EXPOSURE_CONTROLLER=!USER_EXPOSURE_CONTROLLER!"

  set /p "USER_CASH_FILLER_MODE=Cash Filler Mode off/conservative/balanced/balanced_plus_low_beta/benchmark_completion [!AA_CASH_FILLER_MODE!]: "
  if not "!USER_CASH_FILLER_MODE!"=="" set "AA_CASH_FILLER_MODE=!USER_CASH_FILLER_MODE!"

  set /p "USER_CASH_FILLER_MAX=Cash Filler Max Position [!AA_CASH_FILLER_MAX_POSITION!]: "
  if not "!USER_CASH_FILLER_MAX!"=="" set "AA_CASH_FILLER_MAX_POSITION=!USER_CASH_FILLER_MAX!"
  set "AA_CASH_FILLER_MAX_POSITION=!AA_CASH_FILLER_MAX_POSITION:,=.!"

  set /p "USER_CASH_FILLER_MIN=Cash Filler Min Score [!AA_CASH_FILLER_MIN_SCORE!]: "
  if not "!USER_CASH_FILLER_MIN!"=="" set "AA_CASH_FILLER_MIN_SCORE=!USER_CASH_FILLER_MIN!"
  set "AA_CASH_FILLER_MIN_SCORE=!AA_CASH_FILLER_MIN_SCORE:,=.!"

  set /p "USER_BENCHMARK_COMPLETION_TICKER=Benchmark Completion Ticker [!AA_BENCHMARK_COMPLETION_TICKER!]: "
  if not "!USER_BENCHMARK_COMPLETION_TICKER!"=="" set "AA_BENCHMARK_COMPLETION_TICKER=!USER_BENCHMARK_COMPLETION_TICKER!"

  set /p "USER_BENCHMARK_COMPLETION_MAX_WEIGHT=Benchmark Completion Max Weight [!AA_BENCHMARK_COMPLETION_MAX_WEIGHT!]: "
  if not "!USER_BENCHMARK_COMPLETION_MAX_WEIGHT!"=="" set "AA_BENCHMARK_COMPLETION_MAX_WEIGHT=!USER_BENCHMARK_COMPLETION_MAX_WEIGHT!"
  set "AA_BENCHMARK_COMPLETION_MAX_WEIGHT=!AA_BENCHMARK_COMPLETION_MAX_WEIGHT:,=.!"

  set /p "USER_LOW_BETA_MAX=Low-Beta Filler Max Position [!AA_LOW_BETA_FILLER_MAX_POSITION!]: "
  if not "!USER_LOW_BETA_MAX!"=="" set "AA_LOW_BETA_FILLER_MAX_POSITION=!USER_LOW_BETA_MAX!"
  set "AA_LOW_BETA_FILLER_MAX_POSITION=!AA_LOW_BETA_FILLER_MAX_POSITION:,=.!"

  set /p "USER_LOW_BETA_BETA=Low-Beta Filler Beta Max [!AA_LOW_BETA_FILLER_BETA_MAX!]: "
  if not "!USER_LOW_BETA_BETA!"=="" set "AA_LOW_BETA_FILLER_BETA_MAX=!USER_LOW_BETA_BETA!"
  set "AA_LOW_BETA_FILLER_BETA_MAX=!AA_LOW_BETA_FILLER_BETA_MAX:,=.!"

  set /p "USER_LOW_BETA_MIN_SCORE=Low-Beta Filler Min Score [!AA_LOW_BETA_FILLER_MIN_SCORE!]: "
  if not "!USER_LOW_BETA_MIN_SCORE!"=="" set "AA_LOW_BETA_FILLER_MIN_SCORE=!USER_LOW_BETA_MIN_SCORE!"
  set "AA_LOW_BETA_FILLER_MIN_SCORE=!AA_LOW_BETA_FILLER_MIN_SCORE:,=.!"

  set /p "USER_LOW_BETA_MAX_VOL=Low-Beta Filler Max Vol 63 [!AA_LOW_BETA_FILLER_MAX_VOL_63!]: "
  if not "!USER_LOW_BETA_MAX_VOL!"=="" set "AA_LOW_BETA_FILLER_MAX_VOL_63=!USER_LOW_BETA_MAX_VOL!"
  set "AA_LOW_BETA_FILLER_MAX_VOL_63=!AA_LOW_BETA_FILLER_MAX_VOL_63:,=.!"

  set /p "USER_EXPOSURE_RECOVERY=Exposure Recovery Policy off/cause_aware [!AA_EXPOSURE_RECOVERY_POLICY!]: "
  if not "!USER_EXPOSURE_RECOVERY!"=="" set "AA_EXPOSURE_RECOVERY_POLICY=!USER_EXPOSURE_RECOVERY!"

  set /p "USER_CLUSTER_MODE=Cluster Mode static/dynamic_diagnostic/dynamic_guardrail/dynamic_enforced [!AA_CLUSTER_MODE!]: "
  if not "!USER_CLUSTER_MODE!"=="" set "AA_CLUSTER_MODE=!USER_CLUSTER_MODE!"

  set /p "USER_DYN_SHORT=Dynamic Cluster Window Short [!AA_DYNAMIC_CLUSTER_WINDOW_SHORT!]: "
  if not "!USER_DYN_SHORT!"=="" set "AA_DYNAMIC_CLUSTER_WINDOW_SHORT=!USER_DYN_SHORT!"

  set /p "USER_DYN_LONG=Dynamic Cluster Window Long [!AA_DYNAMIC_CLUSTER_WINDOW_LONG!]: "
  if not "!USER_DYN_LONG!"=="" set "AA_DYNAMIC_CLUSTER_WINDOW_LONG=!USER_DYN_LONG!"

  set /p "USER_DYN_CORR=Dynamic Cluster Corr Threshold [!AA_DYNAMIC_CLUSTER_CORR_THRESHOLD!]: "
  if not "!USER_DYN_CORR!"=="" set "AA_DYNAMIC_CLUSTER_CORR_THRESHOLD=!USER_DYN_CORR!"
  set "AA_DYNAMIC_CLUSTER_CORR_THRESHOLD=!AA_DYNAMIC_CLUSTER_CORR_THRESHOLD:,=.!"

  set /p "USER_DYN_OVERLAP=Dynamic Cluster Min Overlap [!AA_DYNAMIC_CLUSTER_MIN_OVERLAP!]: "
  if not "!USER_DYN_OVERLAP!"=="" set "AA_DYNAMIC_CLUSTER_MIN_OVERLAP=!USER_DYN_OVERLAP!"
  set "AA_DYNAMIC_CLUSTER_MIN_OVERLAP=!AA_DYNAMIC_CLUSTER_MIN_OVERLAP:,=.!"

  set /p "USER_REPRO_MODE=Reproducibility Mode normal/strict [!AA_REPRODUCIBILITY_MODE!]: "
  if not "!USER_REPRO_MODE!"=="" set "AA_REPRODUCIBILITY_MODE=!USER_REPRO_MODE!"

  set /p "USER_EXTRA=Zusatzflags fuer active_alpha_model.py [!AA_ADDITIONAL_MODEL_ARGS!]: "
  if not "!USER_EXTRA!"=="" set "AA_ADDITIONAL_MODEL_ARGS=!USER_EXTRA!"
)

set "CFG=%~dp0active_alpha_user_config.bat"
> "%CFG%" echo @echo off
>> "%CFG%" echo rem Auto-generated by run_active_alpha_settings_wizard.bat
>> "%CFG%" echo set "AA_BENCHMARK=!AA_BENCHMARK!"
>> "%CFG%" echo set "AA_START_DATE=!AA_START_DATE!"
>> "%CFG%" echo set "AA_SIGNAL_LOOKBACK_YEARS=!AA_SIGNAL_LOOKBACK_YEARS!"
>> "%CFG%" echo set "AA_BACKTEST_CAPITAL=!AA_BACKTEST_CAPITAL!"
>> "%CFG%" echo set "AA_RESEARCH_BACKTEST_CAPITAL=!AA_RESEARCH_BACKTEST_CAPITAL!"
>> "%CFG%" echo set "AA_PAPER_CAPITAL=!AA_PAPER_CAPITAL!"
>> "%CFG%" echo set "AA_MAX_GROSS_EXPOSURE=!AA_MAX_GROSS_EXPOSURE!"
>> "%CFG%" echo set "AA_BACKTEST_TICKER_SOURCE=!AA_BACKTEST_TICKER_SOURCE!"
>> "%CFG%" echo set "AA_PAPER_TICKER_SOURCE=!AA_PAPER_TICKER_SOURCE!"
>> "%CFG%" echo set "AA_TICKER_CACHE_DIR=!AA_TICKER_CACHE_DIR!"
>> "%CFG%" echo set "AA_TICKER_CACHE_MAX_AGE_DAYS=!AA_TICKER_CACHE_MAX_AGE_DAYS!"
>> "%CFG%" echo set "AA_MEMBERSHIP_FILE=!AA_MEMBERSHIP_FILE!"
>> "%CFG%" echo set "AA_BACKTEST_MEMBERSHIP_MODE=!AA_BACKTEST_MEMBERSHIP_MODE!"
>> "%CFG%" echo set "AA_PAPER_MEMBERSHIP_MODE=!AA_PAPER_MEMBERSHIP_MODE!"
>> "%CFG%" echo set "AA_ASSET_MASTER_FILE=!AA_ASSET_MASTER_FILE!"
>> "%CFG%" echo set "AA_UNIVERSE_MODE=!AA_UNIVERSE_MODE!"
>> "%CFG%" echo set "AA_UNIVERSE_TOP_N=!AA_UNIVERSE_TOP_N!"
>> "%CFG%" echo set "AA_UNIVERSE_ADV_LOOKBACK=!AA_UNIVERSE_ADV_LOOKBACK!"
>> "%CFG%" echo set "AA_UNIVERSE_MIN_ADV=!AA_UNIVERSE_MIN_ADV!"
>> "%CFG%" echo set "AA_UNIVERSE_MIN_PRICE=!AA_UNIVERSE_MIN_PRICE!"
>> "%CFG%" echo set "AA_UNIVERSE_MIN_HISTORY_DAYS=!AA_UNIVERSE_MIN_HISTORY_DAYS!"
>> "%CFG%" echo set "AA_HORIZON=!AA_HORIZON!"
>> "%CFG%" echo set "AA_REBALANCE_EVERY=!AA_REBALANCE_EVERY!"
>> "%CFG%" echo set "AA_TOP_K=!AA_TOP_K!"
>> "%CFG%" echo set "AA_MAX_POSITION=!AA_MAX_POSITION!"
>> "%CFG%" echo set "AA_GOOD_REGIME_EXPOSURE=!AA_GOOD_REGIME_EXPOSURE!"
>> "%CFG%" echo set "AA_BAD_REGIME_EXPOSURE=!AA_BAD_REGIME_EXPOSURE!"
>> "%CFG%" echo set "AA_RISK_ON_EXPOSURE_FLOOR=!AA_RISK_ON_EXPOSURE_FLOOR!"
>> "%CFG%" echo set "AA_MIN_EDGE=!AA_MIN_EDGE!"
>> "%CFG%" echo set "AA_LCB_Z=!AA_LCB_Z!"
>> "%CFG%" echo set "AA_LCB_SCALE=!AA_LCB_SCALE!"
>> "%CFG%" echo set "AA_COST_BPS=!AA_COST_BPS!"
>> "%CFG%" echo set "AA_MAX_ANN_VOL=!AA_MAX_ANN_VOL!"
>> "%CFG%" echo set "AA_MAX_SECTOR=!AA_MAX_SECTOR!"
>> "%CFG%" echo set "AA_MAX_ISSUER=!AA_MAX_ISSUER!"
>> "%CFG%" echo set "AA_MAX_CORRELATION_CLUSTER=!AA_MAX_CORRELATION_CLUSTER!"
>> "%CFG%" echo set "AA_MAX_PORTFOLIO_BETA=!AA_MAX_PORTFOLIO_BETA!"
>> "%CFG%" echo set "AA_BETA_CAP_MODE=!AA_BETA_CAP_MODE!"
>> "%CFG%" echo set "AA_DYNAMIC_BETA_RISK_OFF=!AA_DYNAMIC_BETA_RISK_OFF!"
>> "%CFG%" echo set "AA_DYNAMIC_BETA_NORMAL=!AA_DYNAMIC_BETA_NORMAL!"
>> "%CFG%" echo set "AA_DYNAMIC_BETA_RISK_ON=!AA_DYNAMIC_BETA_RISK_ON!"
>> "%CFG%" echo set "AA_DYNAMIC_BETA_STRONG=!AA_DYNAMIC_BETA_STRONG!"
>> "%CFG%" echo set "AA_STATIC_CLUSTER_CAP=!AA_STATIC_CLUSTER_CAP!"
>> "%CFG%" echo set "AA_DYNAMIC_CLUSTER_CAP=!AA_DYNAMIC_CLUSTER_CAP!"
>> "%CFG%" echo set "AA_CLUSTER_CONSTRAINT_MODE=!AA_CLUSTER_CONSTRAINT_MODE!"
>> "%CFG%" echo set "AA_NO_TRADE_BAND=!AA_NO_TRADE_BAND!"
>> "%CFG%" echo set "AA_WEIGHT_SMOOTHING=!AA_WEIGHT_SMOOTHING!"
>> "%CFG%" echo set "AA_MAX_TURNOVER=!AA_MAX_TURNOVER!"
>> "%CFG%" echo set "AA_TRAIN_YEARS=!AA_TRAIN_YEARS!"
>> "%CFG%" echo set "AA_MIN_TRAIN_ROWS=!AA_MIN_TRAIN_ROWS!"
>> "%CFG%" echo set "AA_TAIL_PRUNE_ENABLED=!AA_TAIL_PRUNE_ENABLED!"
>> "%CFG%" echo set "AA_RESIDUAL_WEIGHT_FLOOR=!AA_RESIDUAL_WEIGHT_FLOOR!"
>> "%CFG%" echo set "AA_RESIDUAL_SELL_MIN_VALUE=!AA_RESIDUAL_SELL_MIN_VALUE!"
>> "%CFG%" echo set "AA_ORDER_VALUE_ROUNDING=!AA_ORDER_VALUE_ROUNDING!"
>> "%CFG%" echo set "AA_BROKER_MIN_REMAINING_POSITION_VALUE=!AA_BROKER_MIN_REMAINING_POSITION_VALUE!"
>> "%CFG%" echo set "AA_MAX_N_POSITIONS_SOFT=!AA_MAX_N_POSITIONS_SOFT!"
>> "%CFG%" echo set "AA_MAX_N_POSITIONS_HARD=!AA_MAX_N_POSITIONS_HARD!"
>> "%CFG%" echo set "AA_TAIL_PRUNE_REALLOCATE=!AA_TAIL_PRUNE_REALLOCATE!"
>> "%CFG%" echo set "AA_MAX_TAIL_REALLOCATION_PER_NAME=!AA_MAX_TAIL_REALLOCATION_PER_NAME!"
>> "%CFG%" echo set "AA_TAIL_REALLOCATION_STEP=!AA_TAIL_REALLOCATION_STEP!"
>> "%CFG%" echo set "AA_TAIL_REALLOCATION_ROUNDS=!AA_TAIL_REALLOCATION_ROUNDS!"
>> "%CFG%" echo set "AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER=!AA_TAIL_PRUNE_MIN_EXPOSURE_BUFFER!"
>> "%CFG%" echo set "AA_EXECUTION_POLICY_MODE=!AA_EXECUTION_POLICY_MODE!"
>> "%CFG%" echo set "AA_TRADING212_POLICY=!AA_TRADING212_POLICY!"
>> "%CFG%" echo set "AA_SLIPPAGE_BPS=!AA_SLIPPAGE_BPS!"
>> "%CFG%" echo set "AA_MARKET_IMPACT_BPS=!AA_MARKET_IMPACT_BPS!"
>> "%CFG%" echo set "AA_TRADING212_FX_BPS=!AA_TRADING212_FX_BPS!"
>> "%CFG%" echo set "AA_TRADING212_SEC_FEE_RATE=!AA_TRADING212_SEC_FEE_RATE!"
>> "%CFG%" echo set "AA_TRADING212_FINRA_TAF_PER_SHARE=!AA_TRADING212_FINRA_TAF_PER_SHARE!"
>> "%CFG%" echo set "AA_FRACTIONAL=!AA_FRACTIONAL!"
>> "%CFG%" echo set "AA_PRICE_LOOKBACK_DAYS=!AA_PRICE_LOOKBACK_DAYS!"
>> "%CFG%" echo set "AA_PRICE_INTERVAL=!AA_PRICE_INTERVAL!"
>> "%CFG%" echo set "AA_BACKTEST_OUT_DIR=!AA_BACKTEST_OUT_DIR!"
>> "%CFG%" echo set "AA_PAPER_MODEL_OUT_DIR=!AA_PAPER_MODEL_OUT_DIR!"
>> "%CFG%" echo set "AA_PAPER_DIR=!AA_PAPER_DIR!"
>> "%CFG%" echo set "AA_ALPHA_MODEL_MODE=!AA_ALPHA_MODEL_MODE!"
>> "%CFG%" echo set "AA_EXTRA_BENCHMARKS=!AA_EXTRA_BENCHMARKS!"
>> "%CFG%" echo set "AA_NAIVE_MOMENTUM_VARIANTS=!AA_NAIVE_MOMENTUM_VARIANTS!"
>> "%CFG%" echo set "AA_BOOTSTRAP_ITERATIONS=!AA_BOOTSTRAP_ITERATIONS!"
>> "%CFG%" echo set "AA_SKIP_NAIVE_MOMENTUM_BASELINE=!AA_SKIP_NAIVE_MOMENTUM_BASELINE!"
>> "%CFG%" echo set "AA_SKIP_STATISTICAL_DIAGNOSTICS=!AA_SKIP_STATISTICAL_DIAGNOSTICS!"
>> "%CFG%" echo set "AA_SKIP_CUSTOM_BENCHMARKS=!AA_SKIP_CUSTOM_BENCHMARKS!"
>> "%CFG%" echo set "AA_SKIP_FEATURE_PARQUET_WRITE=!AA_SKIP_FEATURE_PARQUET_WRITE!"
>> "%CFG%" echo set "AA_NO_PLOT=!AA_NO_PLOT!"
>> "%CFG%" echo set "AA_RISK_OFF_SELECTION_MODE=!AA_RISK_OFF_SELECTION_MODE!"
>> "%CFG%" echo set "AA_RISK_OFF_MOMENTUM_VARIANT=!AA_RISK_OFF_MOMENTUM_VARIANT!"
>> "%CFG%" echo set "AA_RISK_OFF_MOMENTUM_WEIGHT=!AA_RISK_OFF_MOMENTUM_WEIGHT!"
>> "%CFG%" echo set "AA_RISK_OFF_GATE_MODE=!AA_RISK_OFF_GATE_MODE!"
>> "%CFG%" echo set "AA_RISK_OFF_MOMENTUM_RESCUE_QUANTILE=!AA_RISK_OFF_MOMENTUM_RESCUE_QUANTILE!"
>> "%CFG%" echo set "AA_RISK_OFF_FORCE_EXIT_ENABLED=!AA_RISK_OFF_FORCE_EXIT_ENABLED!"
>> "%CFG%" echo set "AA_NAIVE_DETAILED_REPORTING=!AA_NAIVE_DETAILED_REPORTING!"
>> "%CFG%" echo set "AA_NAIVE_DETAILED_VARIANTS=!AA_NAIVE_DETAILED_VARIANTS!"
>> "%CFG%" echo set "AA_NAIVE_POSITION_CONTRIBUTIONS=!AA_NAIVE_POSITION_CONTRIBUTIONS!"
>> "%CFG%" echo set "AA_FORCE_REBUILD_PREDICTIONS=!AA_FORCE_REBUILD_PREDICTIONS!"
>> "%CFG%" echo set "AA_PRICE_CACHE_TTL_HOURS=!AA_PRICE_CACHE_TTL_HOURS!"
>> "%CFG%" echo set "AA_RANDOM_SEED=!AA_RANDOM_SEED!"
>> "%CFG%" echo set "AA_RISK_REGIME_MODE=!AA_RISK_REGIME_MODE!"
>> "%CFG%" echo set "AA_EXPOSURE_CONTROLLER=!AA_EXPOSURE_CONTROLLER!"
>> "%CFG%" echo set "AA_CASH_FILLER_MODE=!AA_CASH_FILLER_MODE!"
>> "%CFG%" echo set "AA_CASH_FILLER_MAX_POSITION=!AA_CASH_FILLER_MAX_POSITION!"
>> "%CFG%" echo set "AA_CASH_FILLER_MIN_SCORE=!AA_CASH_FILLER_MIN_SCORE!"
>> "%CFG%" echo set "AA_BENCHMARK_COMPLETION_TICKER=!AA_BENCHMARK_COMPLETION_TICKER!"
>> "%CFG%" echo set "AA_BENCHMARK_COMPLETION_MAX_WEIGHT=!AA_BENCHMARK_COMPLETION_MAX_WEIGHT!"
>> "%CFG%" echo set "AA_LOW_BETA_FILLER_MAX_POSITION=!AA_LOW_BETA_FILLER_MAX_POSITION!"
>> "%CFG%" echo set "AA_LOW_BETA_FILLER_BETA_MAX=!AA_LOW_BETA_FILLER_BETA_MAX!"
>> "%CFG%" echo set "AA_LOW_BETA_FILLER_MIN_SCORE=!AA_LOW_BETA_FILLER_MIN_SCORE!"
>> "%CFG%" echo set "AA_LOW_BETA_FILLER_MAX_VOL_63=!AA_LOW_BETA_FILLER_MAX_VOL_63!"
>> "%CFG%" echo set "AA_EXPOSURE_RECOVERY_POLICY=!AA_EXPOSURE_RECOVERY_POLICY!"
>> "%CFG%" echo set "AA_CLUSTER_MODE=!AA_CLUSTER_MODE!"
>> "%CFG%" echo set "AA_DYNAMIC_CLUSTER_WINDOW_SHORT=!AA_DYNAMIC_CLUSTER_WINDOW_SHORT!"
>> "%CFG%" echo set "AA_DYNAMIC_CLUSTER_WINDOW_LONG=!AA_DYNAMIC_CLUSTER_WINDOW_LONG!"
>> "%CFG%" echo set "AA_DYNAMIC_CLUSTER_CORR_THRESHOLD=!AA_DYNAMIC_CLUSTER_CORR_THRESHOLD!"
>> "%CFG%" echo set "AA_DYNAMIC_CLUSTER_MIN_OVERLAP=!AA_DYNAMIC_CLUSTER_MIN_OVERLAP!"
>> "%CFG%" echo set "AA_REPRODUCIBILITY_MODE=!AA_REPRODUCIBILITY_MODE!"
>> "%CFG%" echo set "AA_N_JOBS=!AA_N_JOBS!"
>> "%CFG%" echo set "AA_CPU_CORES=!AA_CPU_CORES!"
>> "%CFG%" echo set "AA_PARALLEL_BACKTEST_BACKEND=!AA_PARALLEL_BACKTEST_BACKEND!"
>> "%CFG%" echo set "AA_SYSTEM_RAM_GB=!AA_SYSTEM_RAM_GB!"
>> "%CFG%" echo set "AA_PARALLEL_PROFILE=!AA_PARALLEL_PROFILE!"
>> "%CFG%" echo set "AA_REUSE_FEATURE_CACHE=!AA_REUSE_FEATURE_CACHE!"
>> "%CFG%" echo set "AA_REUSE_PREDICTION_CACHE=!AA_REUSE_PREDICTION_CACHE!"
>> "%CFG%" echo set "AA_SKIP_DOWNLOAD_IF_CACHED=!AA_SKIP_DOWNLOAD_IF_CACHED!"
>> "%CFG%" echo set "AA_SHARED_CACHE_DIR=!AA_SHARED_CACHE_DIR!"
>> "%CFG%" echo set "AA_NO_NAIVE_OVERLAP=!AA_NO_NAIVE_OVERLAP!"
>> "%CFG%" echo set "AA_ADDITIONAL_MODEL_ARGS=!AA_ADDITIONAL_MODEL_ARGS!"

echo.
echo [OK] Gespeichert: active_alpha_user_config.bat
echo.
call "%~dp0show_active_alpha_config.bat"
endlocal
exit /b 0

:ValidatePolicyInputs
set "AA_TRADING212_POLICY=!AA_TRADING212_POLICY: =!"
set "AA_EXECUTION_POLICY_MODE=!AA_EXECUTION_POLICY_MODE: =!"
if /I not "!AA_TRADING212_POLICY!"=="conservative" if /I not "!AA_TRADING212_POLICY!"=="balanced" if /I not "!AA_TRADING212_POLICY!"=="active" if /I not "!AA_TRADING212_POLICY!"=="threshold" (
  echo [WARN] Unbekannte Trading-212-Policy "!AA_TRADING212_POLICY!". Fallback: balanced
  set "AA_TRADING212_POLICY=balanced"
)
if /I not "!AA_EXECUTION_POLICY_MODE!"=="manual" if /I not "!AA_EXECUTION_POLICY_MODE!"=="capital_curve" (
  echo [WARN] Unbekannter Execution Policy Mode "!AA_EXECUTION_POLICY_MODE!". Fallback: capital_curve
  set "AA_EXECUTION_POLICY_MODE=capital_curve"
)
exit /b 0
