#!/usr/bin/env bash
# Optional Phase 4b: NTFS → ext4 (only when Windows D: is abandoned).
# Does NOT run destructive steps automatically — prints operator checklist.
set -euo pipefail
PART="${AA_NVME_PART:-/dev/nvme0n1p1}"
MOUNT="${AA_NVME_MOUNT:-/mnt/active-alpha-nvme}"
BACKUP="${AA_NVME_EXT4_BACKUP:-$HOME/active_alpha_nvme_backup}"

echo "=== Active Alpha — NVMe ext4 Migration (manuell) ==="
echo ""
echo "Voraussetzung: Windows nutzt Laufwerk D: nicht mehr."
echo "Partition: $PART"
echo "Ziel:      $MOUNT (ext4)"
echo ""
echo "1) Daten sichern (active_alpha_fast_data):"
echo "   rsync -aH --info=progress2 \\"
echo "     /run/media/*/active_alpha_fast_data/ \\"
echo "     $BACKUP/active_alpha_fast_data/"
echo ""
echo "2) Partition formatieren (DESTRUKTIV):"
echo "   sudo umount $PART 2>/dev/null || true"
echo "   sudo mkfs.ext4 -L active-alpha-nvme $PART"
echo ""
echo "3) Mount + fstab:"
echo "   sudo mkdir -p $MOUNT"
echo "   UUID=\$(sudo blkid -s UUID -o value $PART)"
echo "   echo \"UUID=\$UUID  $MOUNT  ext4  defaults,nofail  0  2\" | sudo tee -a /etc/fstab"
echo "   sudo mount $MOUNT"
echo ""
echo "4) Daten zurück + Symlinks:"
echo "   sudo rsync -aH $BACKUP/active_alpha_fast_data/ $MOUNT/active_alpha_fast_data/"
echo "   sudo chown -R \$USER:\$USER $MOUNT"
echo "   cd ~/active_alpha_model && bash tools/setup_nvme_storage.sh"
echo ""
echo "Bis dahin: NTFS + udisks/fstab via tools/mount_nvme_active_alpha.sh reicht."
